; PlatformIO Project Configuration File

[env:smart-car]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_flags = -I include

lib_deps = 
	knolleary/PubSubClient
	mikalhart/TinyGPSPlus
	robtillaart/PCF8574@^0.4.4
	bblanchon/ArduinoJson@^7.2.2
